services:
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5050"
    environment:
      FLASK_DEBUG: "true"
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/vacanciesdb"
      MONGO_HOST: "mongodb"
      RABBIT_HOST: "rabbit_host"
    hostname: "web"

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=INFO --purge --pool=solo
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/vacanciesdb"
      RABBIT_HOST: "rabbit_host"
    hostname: "celery_worker"

  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    hostname: "postgres"

  mongo:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    hostname: 'rabbit_host'
