services:
  web:
    build: .
    ports:
      - "5000:5050"
    environment:
      FLASK_DEBUG: "true"
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/vacanciesdb"
      MONGO_HOST: "mongodb"
      EMAIL_PASSWORD: "hhcfdwbcqsteczok"
    hostname: "web"

  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    hostname: "postgres"

  mongo:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
